# Generated by Django 5.1.5 on 2025-04-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_category', models.CharField(max_length=50)),
                ('menu_type', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=10)),
                ('menu_quantity_half', models.CharField(blank=True, max_length=20, null=True)),
                ('menu_quantity_full', models.CharField(blank=True, max_length=20, null=True)),
                ('menu_half_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('menu_full_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('menu_isActive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_menu_details',
            },
        ),
    ]
