# Generated by Django 4.2 on 2025-04-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_menudetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
