# Generated by Django 5.2 on 2025-05-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
