# Generated by Django 5.2 on 2025-05-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_order_updated_at_alter_orderdetail_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
