# Generated by Django 5.2 on 2025-05-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
