# Generated by Django 4.2 on 2025-05-27 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_orderdetail_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_number', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tablemaster_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tablemaster_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
