# Generated by Django 4.2 on 2025-05-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_tablemaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemaster',
            name='table_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
