# Generated by Django 4.2 on 2025-05-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_alter_tablemaster_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudetails',
            name='seating_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
