# Generated by Django 5.2 on 2025-05-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_order_grand_total_order_gst_amount_order_gst_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='daily_order_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
