# Generated by Django 5.2 on 2025-05-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_order_daily_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
