# Generated by Django 5.2 on 2025-05-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
