# Generated by Django 5.2 on 2025-12-27 05:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_order_table_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('measurement_type', models.CharField(choices=[('PORTION', 'Portion (Half/Full)'), ('QUANTITY', 'Quantity (1, 2, 3...)'), ('VOLUME_ML', 'Volume (ml)'), ('BOTTLE', 'Bottles'), ('WEIGHT', 'Weight (gm/kg)')], default='PORTION', max_length=20)),
                ('unit_name', models.CharField(blank=True, max_length=20)),
                ('allow_custom', models.BooleanField(default=False)),
                ('portion_small_name', models.CharField(default='Half', max_length=20)),
                ('portion_large_name', models.CharField(default='Full', max_length=20)),
                ('default_quantity', models.IntegerField(default=1)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'tbl_categories',
            },
        ),
    ]
