# Generated by Django 5.2 on 2025-12-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
