# Generated by Django 5.2 on 2025-12-27 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_alter_category_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
