# Generated by Django 5.2 on 2025-12-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudetails',
            name='measurement_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='menudetails',
            name='menu_measurement',
            field=models.CharField(choices=[('half_full', 'Half/Full Portion'), ('piece', 'Per Piece'), ('ml', 'Milliliters'), ('plate', 'Per Plate'), ('bottle', 'Per Bottle'), ('glass', 'Per Glass'), ('slice', 'Per Slice'), ('dozen', 'Per Dozen'), ('kg', 'Per Kilogram'), ('gram', 'Per Gram')], default='half_full', max_length=20),
        ),
    ]
